## File handleing
* It is used when you want to store arrays permanently and use
* them later without recreating them .

In [ ]:
import numpy as np 
name = np.array(['shivesh','anjali','sumnat','soulmaya'])
age = np.array([19,20,30,40])
roll_no = np.array([1,2,3,4,5])
student = np.array(["shivesh",19,"shudip",99])
print(name)
print(age)
print(roll_no)
print(np.save("age.npy",age))

['shivesh' 'anjali' 'sumnat' 'soulmaya']
[19 20 30 40]
[1 2 3 4 5]
None


In [ ]:
np.save("age.npy",age)
print("\nage.npy file created successfully")




Mark.npy file created successfully


## save multiple files

In [22]:
np.savez(
    "shivesh.npz",
    name = name,
    age = age,
    roll_no = roll_no
)
print("saved")

saved


## load the save file

In [19]:
stu = np.load("shivesh.npz")
print(stu)

NpzFile 'shivesh.npz' with keys: name, age


## save as text file

In [32]:
np.savetxt(
    "d.txt",
    name,
    fmt = "%s"

)

In [24]:
np.savetxt(
    "save.txt"
    , age
    , fmt="%d"

)

##  Load The Text file

In [27]:
text_data = np.loadtxt(
    "save.txt",
    dtype=int,
    )

print("\nmark.text file load successfully")

print(text_data)


mark.text file load successfully
[19 20 30 40]


In [33]:
text_name = np.loadtxt(
    "d.txt",
    dtype=str)

print("\nname.text file load successfully")

print(text_name)


name.text file load successfully
['shivesh' 'anjali' 'sumnat' 'soulmaya']


## Save as CSV file : comma separate values

In [38]:
student_rec = np.array([
    [101,85],
    [102,86],
    [103,87]
])
np.savetxt(
    "student.csv",
    student_rec,
    delimiter= ",",
    fmt = "%d"
)
print("\nstudents.csv file save successfully")


students.csv file save successfully


## Load csv file

In [40]:
csv_data = np.loadtxt(
    "student.csv",
    delimiter=",",
    dtype=int)
print("\nData loaded from CSV")
print(csv_data)


Data loaded from CSV
[[101  85]
 [102  86]
 [103  87]]


In [42]:

student1 = np.array([
    [101,'xyz',85],
    [102,'pqr',56],
    [103,'abc',43],
    [104,'lmn',78]])
np.savetxt(
    "students1.csv",
    student1,
    delimiter=",",
    fmt="%s")
print("\nstudents.csv file save successful")


students.csv file save successful


In [43]:
csv_data1 = np.loadtxt(
    "students1.csv",
    delimiter=",",
    dtype=str
    )
print("\nData loaded from CSV")
print(csv_data1)



Data loaded from CSV
[['101' 'xyz' '85']
 ['102' 'pqr' '56']
 ['103' 'abc' '43']
 ['104' 'lmn' '78']]
