In [2]:
import numpy as np

In [4]:
d = np.array([1.0,2.3,3.4,4.4])
a_int = d.astype(int)
print(d)
print(d.dtype)
print(a_int)
print(a_int.dtype)


[1.  2.3 3.4 4.4]
float64
[1 2 3 4]
int64


In [18]:
d = np.array([1,2,3,4,5])
print(d[-1])
print(d[0])
print(d.shape)

5
1
(5,)


In [23]:
c =np.array([[1,2,3],[4,5,6]])
print(c[0,0])
print(c[0,1])
print(c[0,2])
print(c[1,0])
print(c[1,1])
print(c[1,2])
print("--------")


d = np.array([[[1,2],
               [8,9],
               [10,88]]
               ,[[2,4],
                 [3,5],
                 [99,77]]])
print(d[1][1][1])
print(d)
print(d[0,1,1])
print(d[1,0,0])
print(d.ndim)
print(d.shape)


1
2
3
4
5
6
--------
5
[[[ 1  2]
  [ 8  9]
  [10 88]]

 [[ 2  4]
  [ 3  5]
  [99 77]]]
9
2
3
(2, 3, 2)
