## aggregation function

In [17]:
import numpy as np

arr1 =np.array([1,2,3,4,5,6,7,8])
arr2 =np.array([10,20,30,40,50,60,70,80])

print(np.greater(arr2,arr1))
print(np.greater(arr1,arr2))
print("-------------------")
print(np.greater_equal(arr2,arr1))
print(np.greater_equal(arr1,arr2))
print("-------------------")
print(np.less(arr1,arr2))
print(np.less_equal(arr1,arr2))
print("-------------------")
print(np.equal(arr1,arr2))
print(np.not_equal(arr1,arr2))
print("-------------------")
print(np.subtract(arr1,arr2))
print(np.add(arr1,arr2))
print(np.multiply(arr1,arr2))
print(np.divide(arr1,arr2))
print(np.floor_divide(arr1,arr2))
print("-------------------")
# print(np.max(arr2,arr1))
# print(np.min(arr1,arr2))
print("-------------------")
print(np.square(arr1,arr2))
print("-------------------")
# print(np.sqrt(arr1,arr2))
print(np.abs(arr1,arr2))
print("-------------------")
# print(np.mean(arr1,arr2))
# print(np.median(arr1,arr2))
# print(np.std(arr1,arr2))
# print(np.var(arr1,arr2))
# print(np.mod(arr1,arr2))
# print(np.power(arr1,arr2))

[ True  True  True  True  True  True  True  True]
[False False False False False False False False]
-------------------
[ True  True  True  True  True  True  True  True]
[False False False False False False False False]
-------------------
[ True  True  True  True  True  True  True  True]
[ True  True  True  True  True  True  True  True]
-------------------
[False False False False False False False False]
[ True  True  True  True  True  True  True  True]
-------------------
[ -9 -18 -27 -36 -45 -54 -63 -72]
[11 22 33 44 55 66 77 88]
[ 10  40  90 160 250 360 490 640]
[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
[0 0 0 0 0 0 0 0]
-------------------
-------------------
[ 1  4  9 16 25 36 49 64]
-------------------
[1 2 3 4 5 6 7 8]
-------------------
