# reshape
* reshape is numpy reference to modify the dimensation of an existing array without changing it data

In [2]:
import numpy as np

arr = np.arange(0,12)
print(arr)
print(arr.reshape(3,4))
print("-----------------")
print(arr.reshape(3,-1))          #-1 calculate autocalculated    Here, -1 tells NumPy: "You figure out the second dimension."
print("-----------------")
print(arr.reshape(2,2,3))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-----------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-----------------
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


# resize
* resize() is used to change the size of an existing array it modify arry permantly and adjust itself. if the new shape required more element than available numpy repeat, the array element. if less shape is required are truncated. 

In [3]:
arr =np.array([1,2,3,4,5,6,7,8,9])
new_arr =np.resize(arr,(3,4))
print(new_arr)

[[1 2 3 4]
 [5 6 7 8]
 [9 1 2 3]]


# flatering covert multiple dimenation into 1D

In [4]:
d= np.array([[10,20,30],
               [40,50,60],
               [70,80,90],
               [100,110,120]])
b = d.flatten()
print(b)

[ 10  20  30  40  50  60  70  80  90 100 110 120]


In [5]:
b = d.ravel()
print(b)

[ 10  20  30  40  50  60  70  80  90 100 110 120]


In [6]:
b = d.reshape(-1)
print(b)

[ 10  20  30  40  50  60  70  80  90 100 110 120]


### Transpose

In [7]:
A = np.array([[10,20,30],[30,40,50]])
print(A.T)
print(A.transpose)
print(id(A))

[[10 30]
 [20 40]
 [30 50]]
<built-in method transpose of numpy.ndarray object at 0x000001358474E4F0>
1329367147760


### Expanding

In [8]:
n = np.array([10,11,12,13,14])
print(n.shape)
w = np.expand_dims(n,axis=1)
print(w)
print(w.shape)

(5,)
[[10]
 [11]
 [12]
 [13]
 [14]]
(5, 1)


### sequeezing removing dimmensional of size 

In [10]:
A =np.array([[1,2,3,5,6]])
print(A)
print(A.shape)
x = np.squeeze(A)
print(x)
print(x.shape)

[[1 2 3 5 6]]
(1, 5)
[1 2 3 5 6]
(5,)
