# math function

## axis based operation

In [11]:
import numpy as np
a = np.array([[10,40,50],[20,30,40]]) 
x = np.sum(a[1],axis = 0)
print(x)
print(sum(a))

90
[30 70 90]


# rounding function
- the function in numpy round the element of an array to specific of element
1. Round()
2. floor()
3. ceil()

In [14]:
a = np.array([12.33,56.4544,455.223,-224.2223])
print(np.round(a))
print(np.round(a,2))
print(np.floor(a))
print(np.ceil(a))



[  12.   56.  455. -224.]
[  12.33   56.45  455.22 -224.22]
[  12.   56.  455. -225.]
[  13.   57.  456. -224.]


## logrithm function(logn,log())

In [17]:
a = np.array([1,22.334,44,62.34])
print(np.log(a))
print(np.log2(a))
print(np.log10(a))
print(np.log(a).round(3))


[0.         3.10611018 3.78418963 4.13260327]
[0.         4.48116975 5.45943162 5.96208625]
[0.         1.34896651 1.64345268 1.7947668 ]
[0.    3.106 3.784 4.133]


## Trigonometric function

In [21]:
a = np.array([10,20,30,40])
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))
print(np.radians(a))
print(np.arcsin(a))
print(np.degrees(np.arcsin(a)))
print(np.degrees(a))

[-0.54402111  0.91294525 -0.98803162  0.74511316]
[-0.83907153  0.40808206  0.15425145 -0.66693806]
[ 0.64836083  2.23716094 -6.4053312  -1.11721493]
[0.17453293 0.34906585 0.52359878 0.6981317 ]
[nan nan nan nan]
[nan nan nan nan]
[ 572.95779513 1145.91559026 1718.87338539 2291.83118052]


C:\Users\shive\AppData\Local\Temp\ipykernel_19384\3022677307.py:6: RuntimeWarning: invalid value encountered in arcsin
  print(np.arcsin(a))
C:\Users\shive\AppData\Local\Temp\ipykernel_19384\3022677307.py:7: RuntimeWarning: invalid value encountered in arcsin
  print(np.degrees(np.arcsin(a)))
