# Array Manipulation
- concatenate()~ used yo join array along an exiting axis.
- stack() ~ joining array by creating a new axis.
- hstack() ~ horizontal stack join array cloumn axis
- vstack ~ vertical stack joins array row wise

## concatenate()

In [7]:
import numpy as np
a = np.array([10,20,30,40,50])
b = np.array([1,2,34,5,6])
c = np.concatenate((a,b),axis=0)
print(c)

[10 20 30 40 50  1  2 34  5  6]


In [8]:
c = np.array([[10,20,30,40,50],[1,2,34,5,6]])
b = np.array([[7,8,9,10,11],[12,13,14,15,16]])
d = np.concatenate((c,b),axis=1)
print(d)

[[10 20 30 40 50  7  8  9 10 11]
 [ 1  2 34  5  6 12 13 14 15 16]]


## stack()

In [11]:
a = np.array([12,20,30,405,606])
b = np.array([1,2,3,55,6])
c = np.stack((a,b))
print(c)

[[ 12  20  30 405 606]
 [  1   2   3  55   6]]


## hstack

In [12]:
c =np.array([6,7,8])
d =np.array([1,23,3])
f =np.hstack((c,d))
print(f)

[ 6  7  8  1 23  3]


## vstack

In [16]:
d =np.array([6,7,8])
c = np.array([1,2,3])
f = np.vstack((d,c))
print(f)

[[6 7 8]
 [1 2 3]]


### splitting array ~ dividing one array into multiple smaller array 
## split() 
- splits an array into equal parts

In [22]:
a =np.array([1,2,3,4,5,6,7,8,9,10])
# only works when equal division is possible
d = np.split(a,2)
print(d)

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]


## array_split()
- works when equal division is not possible

In [ ]:
a = np.array([10,20,30,40,50])
d = np.array_split(a,3)
print(d)


[array([10, 20]), array([30, 40]), array([50])]


## 