# insorting data
## insert

In [2]:
import numpy as np
x = np.array([10,20,30,40,50,66,7,0])
d = np.insert(x,4,4)
print(d)

[10 20 30 40  4 50 66  7  0]


## delete data

In [4]:
x = np.array([10,20,30,40,50,66,7,0])
d = np.delete(x,4)
print(d)

[10 20 30 40 66  7  0]


## append

In [12]:
x = np.array([10,20,30,40,50,66,7,0])
d = np.append(x,55)
c = np.append(x,(2,6,5,677,9))
print(d)
print(c)

[10 20 30 40 50 66  7  0 55]
[ 10  20  30  40  50  66   7   0   2   6   5 677   9]
