# Broadcasting
* it is numpy way of performing operation an array of different shape without making copies on writing slow loop

In [3]:
import numpy as np
a =np.array([[1,2,3],[10,20,30]])
print(a.shape)
b = np.array([10,11,12])
print(b.shape)
result = a+b
print(result)

(2, 3)
(3,)
[[11 13 15]
 [20 31 42]]


In [4]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([10,11,12])
z = a+b
print(z)

[[11 13 15]
 [14 16 18]
 [17 19 21]]
