## Linear algebra

* dot product

In [2]:
import numpy as np
a = np.array([10,20,30])
b =np.array([2,4,6])
result = np.dot(a,b)
print(result)

280


# 2D

In [4]:
a = np.array([[10,30],[2,3]])
b =np.array([[2,9],[7,8]])
result = np.dot(a,b)
print(result)

[[230 330]
 [ 25  42]]


# 3D

In [5]:
a = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
b = np.array([[[9,8,7],[6,5,4],[3,2,2]]])
res = a@b
print(res)

[[[ 30  24  21]
  [ 84  69  60]
  [138 114  99]]]


## Determinant

In [ ]:
a = np.array([[1,2],[3,4]])
print(np.linalg.det(a)) # determint
print(np.linalg.inv(a))  # inverse

-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]
