# Random 
* it is the process of producing number that appear unpredictable
### iteration
- how to go through each element one by one when we need to perfromd different action on each element.

# 2D

In [1]:
import numpy as np

arr = np.array([10,10,30,40,50])

for x in np.nditer(arr):
    x = x*2
    print(x)

print("Final array:", arr)

20
20
60
80
100
Final array: [10 10 30 40 50]


In [2]:
import numpy as np

arr = np.array([10,10,30,40,50])

for x in np.nditer(arr, op_flags=["readwrite"]):
    x[...] = x * 2
    print(x)

print("Final array:", arr)

20
20
60
80
100
Final array: [ 20  20  60  80 100]


In [3]:
a = np.array([10,20,30,40,50])
b = np.array([3,4,5,6,7])
for x,y in np.nditer([a,b]):
    print(x,y)

10 3
20 4
30 5
40 6
50 7


# iteration with index

In [4]:
a = np.array([10,20,30,40,50,60])
for idx, value in np.ndenumerate(a):
    print(idx,value)

(0,) 10
(1,) 20
(2,) 30
(3,) 40
(4,) 50
(5,) 60


In [5]:
a = np.array([[10,20,30,40,50,60],[70,80,90,100,110,120]])
for idx, value in np.ndenumerate(a):
    print(idx,value)

(0, 0) 10
(0, 1) 20
(0, 2) 30
(0, 3) 40
(0, 4) 50
(0, 5) 60
(1, 0) 70
(1, 1) 80
(1, 2) 90
(1, 3) 100
(1, 4) 110
(1, 5) 120


# rand()
* generate random float-point values between 0 to 1

In [6]:
print(np.random.rand())
print("------")
print(np.random.rand(2,3))
print("------")

0.7031161027170392
------
[[0.40946845 0.99381462 0.67257117]
 [0.09211464 0.80407774 0.61812272]]
------


In [8]:
print(np.random.randint(0,10,size=(2,3)))

[[4 6 1]
 [6 5 1]]


# randn()
- generate eansim numbet from the standard normal disrturbution 

In [ ]:
print(np.random.randn())
print(np.random.randn(3))
print(np.random.randn(1,10))

0.7549469846935845
[-0.2371536  -0.30080023 -1.92841343]
[[ 1.80168234 -1.96076834 -0.41962003 -0.87130636 -0.56122411  0.07679006
  -0.21138288 -0.95372491  0.12761476  1.33633992]]


### Random sampling
- It is the process of selecting one or more items randomly from a datasets, list or array, each item has a equal cahnce of being choosen.
## choice()
- Randomly selects element from an array

In [14]:
x = np.arange(1,10)
print(np.random.choice(x,size=3))

[8 6 1]


## shuffle()
- Randomly rerange element of an array 

In [19]:
x = np.array([20,10,30,40,50,60,70,80])
np.random.shuffle(x)
print(x)


[40 80 70 20 30 10 50 60]


## seed()
- A seed is like a starting point for the random number generator.

- If you set the same seed, you’ll always get the same random results.

- Useful for debugging, reproducibility, or when you want consistent outputs.

In [23]:
x = np.array([20,10,30,40,50,60,70,80])

np.random.seed(7)      # set the seed
np.random.shuffle(x)    # shuffle in-place

print(x)


[30 60 20 70 40 10 50 80]
