# probability disturibution
- it descibed hoe random values are separeted over arange. it tells us the like hood of difference out come occuring 
1. uniform distribution
2. normal distribution 
3. binominal distribution

## uniform distribution 
- every value is a sperate range has equal change of occuring

In [2]:
import numpy as np

m = np.random.uniform(1,10,2)
print(m)

[5.57739  2.852795]


## Normal distribution
- values ine dirtibution around a central mean forming a bell-shaped curve
- loc → mean (μ) of the distribution

- scale → standard deviation (σ)

- size → shape of the output array (number of samples)

In [3]:
np.random.normal(loc=50,scale=10,size=10)

array([51.54641301, 33.63937489, 55.86545033, 45.82097539, 48.87232688,
       67.70567167, 33.09309272, 47.19220414, 48.58869598, 43.81654254])

## Binomial distribution
- Key Features
- Trials (n): Number of experiments (e.g., flipping a coin 10 times).

- Probability (p): Chance of success in each trial (e.g., probability of heads = 0.5).

- Random variable (X): Number of successes out of n trials.

- Range: 𝑋 can take values from 0 up to n.

In [6]:
import numpy as np

# Toss a coin 10 times, probability of heads = 0.5
x = np.random.binomial(n=10, p=0.5, size=5)
print(x)


[4 5 2 7 6]


## poisson distribution
-  Key Features
- Events are rare and independent (e.g., number of phone calls per hour, accidents per day).

- Defined by a single parameter: λ (lambda) = average rate of occurrence.

- Random variable 𝑋 = number of events in the interval.

- Possible values: 0,1,2,…(non-negative integers).

In [5]:
import numpy as np

# Average 5 events per interval
x = np.random.poisson(lam=5, size=10)
print(x)


[7 6 2 4 2 7 6 6 3 6]


## Exponential distribution
- Key Features
- Defined by a single parameter: λ (lambda) = rate of occurrence.

- Random variable 𝑋 = time until the next event.

- Always non-negative (𝑋≥0).

- Memoryless property: probability of waiting longer doesn’t depend on how much time has already passed.

In [7]:
import numpy as np

# Average waiting time = 5 units (scale=5)
samples = np.random.exponential(scale=5, size=10)
print(samples)


[ 5.28534362  1.31623728  0.27278126  7.88411653  0.36265998  4.25662004
  5.32208263  2.18042698  8.51164342 12.01831833]


In [ ]:
bass etna hiii