In [ ]:
numpy is short from of numerical python. it is a open source library that provdies support for large multi dimensional array 4 mattix,
 along with large collection of high -level math function to operate on there array, created by travis oliphant in 2005. 

numpy array is a homogenoues data structure. it was optimize  c language style storage where actual values are store in contigous.

In [1]:
import numpy as np

In [7]:
#1D
A = np.array([1,2,3,4,5])
print(A)
print(A.ndim)

#2D
B = np.array([["shivesh"],
              ["anjlai"]])
print(B)
print(B.ndim)

#3D
c = np.array([[[1,2,3,4],
               [5,6,7,8]]])
print(c)
print(c.ndim)

[1 2 3 4 5]
1
[['shivesh']
 ['anjlai']]
2
[[[1 2 3 4]
  [5 6 7 8]]]
3


In [18]:
d = np.zeros(4)
print(d)
f = np.ones(8)
print(f)
g = np.empty(3)
print(g)

[0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1.]
[2.33419537e-312 2.29175545e-312 2.22809558e-312]


In [21]:
#arnage(start,stop,step)
d = np.arange(0,10)
print(d)
s = np.arange(1,10,2)
print(s)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [23]:
d = np.linspace(1,10,4)
print(d)

[ 1.  4.  7. 10.]


In [30]:
d = np.array([[1,2,3],
             [4,5,6]])
print(d)
print(d.shape)
print(d.size)
print(d.ndim)
print(d.dtype)
print(d.itemsize)
print(d.nbytes)
print(d.dtype.type)

[[1 2 3]
 [4 5 6]]
(2, 3)
6
2
int64
8
48
<class 'numpy.int64'>


In [35]:
d = np.array([[[1],
               [2],
               [3]],
               [[4],
                [5],
                [6]]],dtype=np.int16)
print(d.ndim)
print(d.dtype)
print(d.dtype.type)

3
int16
<class 'numpy.int16'>
