# reshape
* reshape is numpy reference to modify the dimensation of an existing array without changing it data

In [2]:
import numpy as np

arr = np.arange(0,12)
print(arr)
print(arr.reshape(3,4))
print("-----------------")
print(arr.reshape(3,-1))          #-1 calculate autocalculated    Here, -1 tells NumPy: "You figure out the second dimension."
print("-----------------")
print(arr.reshape(2,2,3))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-----------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-----------------
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


# resize
* resize() is used to change the size of an existing array it modify arry permantly and adjust itself. if the new shape required more element than available numpy repeat, the array element. if less shape is required are truncated. 

In [5]:
arr =np.array([1,2,3,4,5,6,7,8,9])
new_arr =np.resize(arr,(3,4))
print(new_arr)

[[1 2 3 4]
 [5 6 7 8]
 [9 1 2 3]]


# flatering covert multiple dimenation into 1D