In [2]:
import numpy as np

In [3]:
d = np.array([10,20,30,40,50,60,70,80])
print(d[0:7])
print(d[:7:2])
print(d[0:7:-1]) # empty because 
#resverse slicing
print(d[6:0:-1])
print(d[::-1])

[10 20 30 40 50 60 70]
[10 30 50 70]
[]
[70 60 50 40 30 20]
[80 70 60 50 40 30 20 10]


In [4]:
d = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(d[:2,1:])
print(d[1:3,0:2])

[[2 3]
 [5 6]]
[[4 5]
 [7 8]]


## negative indexing


In [10]:
a = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
print(a)
print("--------")
print(a[-1])
print("--------")
print(a[-2,-3])
print("--------")
print(a[-1,-3])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
--------
[70 80 90]
--------
40
--------
70


## boolean indexing 

In [16]:
b =np.array([40,60,70,50,59,40,49])
score = b>60 
print(score)
print("---------")
a = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
c = a>40
print(c)

[False False  True False False False False]
---------
[[False False False]
 [False  True  True]
 [ True  True  True]]
