In [1]:
import numpy as np

In [ ]:
d = np.array([10,20,30,40,50,60,70,80])
print(d[0:7])
print(d[:7:2])
print(d[0:7:-1]) # empty because 
#resverse slicing
print(d[6:0:-1])
print(d[::-1])

[10 20 30 40 50 60 70]
[10 30 50 70]
[]
[70 60 50 40 30 20]
[80 70 60 50 40 30 20 10]


In [24]:
d = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(d[:2,1:])
print(d[1:3,0:2])

[[2 3]
 [5 6]]
[[4 5]
 [7 8]]


In [ ]:
#negative indexing
